// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe2y0LCRTZoJFIYuoeIowAFbr0IsC_GHA',
    appId: '1:655377908506:web:01b9890059baf3ba9362a3',
    messagingSenderId: '655377908506',
    projectId: 'flutterfirenote-f3369',
    authDomain: 'flutterfirenote-f3369.firebaseapp.com',
    storageBucket: 'flutterfirenote-f3369.firebasestorage.app',
    measurementId: 'G-N2G94XTF7S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2__GCR1ZuKiQ9fI92HLLbng2DrJVtzII',
    appId: '1:655377908506:ios:778f6d221854bfaf9362a3',
    messagingSenderId: '655377908506',
    projectId: 'flutterfirenote-f3369',
    storageBucket: 'flutterfirenote-f3369.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzPRWKwRParMATKQXgnQdo8jr-Za90GR0',
    appId: '1:655377908506:android:038f08b21e095b369362a3',
    messagingSenderId: '655377908506',
    projectId: 'flutterfirenote-f3369',
    storageBucket: 'flutterfirenote-f3369.firebasestorage.app',
  );

}